server:
  port: 8080
spring:
  cloud:
    function:
      routing-expression: "headers['version'] == 'v1' ? 'fooEventConsumerV1' : 'fooEventConsumerV2'"
    stream:
      bindings:
        fooEventSupplier-out-0:
          contentType: application/json
          destination: foo-event-topic
        functionRouter-in-0:
          contentType: application/json
          destination: foo-event-topic
          group: foo
      kafka:
        binder:
          brokers: "localhost:9092"
          healthTimeout: 10
          requiredAcks: 1
          autoCreateTopics: true # true - only for develop and test environments
          autoAddPartitions: true
          minPartitionCount: 1
          replicationFactor: 1
logging:
  level:
    org.springframework: INFO
    com.tuimm: DEBUG
